name: Deploy to Dokploy VPS

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
        cat ~/.ssh/id_ed25519.pub
        eval $(ssh-agent -s)
        ssh-add -v ~/.ssh/id_ed25519
    
    - name: Debug SSH Connection
      run: |
        echo "Attempting SSH connection..."
        ssh -vvv -o StrictHostKeyChecking=no root@167.235.75.153 "echo 'SSH connection test'"
      continue-on-error: true
    
    - name: Deploy to VPS
      run: |
        echo "Attempting deployment..."
        ssh -o StrictHostKeyChecking=no root@167.235.75.153 "mkdir -p /var/www/html/dahalan.org/testworkflow/"
        scp -o StrictHostKeyChecking=no -r src/* root@167.235.75.153:/var/www/html/dahalan.org/testworkflow/
        echo "Deployment files transferred successfully"
      
    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        response=$(curl -s -w "%{http_code}" https://dahalan.org/testworkflow/index.html)
        if [ "$response" -eq 200 ]; then
          echo "Deployment successful! Website is live."
        else
          echo "Deployment verification failed. HTTP status: $response"
          exit 1
        fi
